---
# github-service
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: github-service
  namespace: keptn
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/minScale: "1"
        spec:
          container:
            image: keptn/github-service:latest
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: github-service-keptn-channel-subscription
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: keptn-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: github-service
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: github-service-new-artifact-subscription
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: new-artifact
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: github-service
---
# pitometer-service
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: pitometer-service
  namespace: keptn
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: keptn/pitometer-service:latest
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: pitometer-service-tests-finished-subscription
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: tests-finished
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: pitometer-service
---
# servicenow-service
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: servicenow-service
  namespace: keptn
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: keptn/servicenow-service:latest
            imagePullPolicy: Always
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: servicenow-service-problem-subscription
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: problem
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: servicenow-service
---
# helm-service
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helm-service
  namespace: keptn
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/minScale: "1"
        spec:
          container:
            image: keptn/helm-service:latest
            imagePullPolicy: Always
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: helm-service-configuration-changed-subscription
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: configuration-changed
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: helm-service
