apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: openshift-route-service-keptn-channel-subscription
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: keptn-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: openshift-route-service